### ISSUE TITLE
Twitter Hashtags here differ from wiki Congress Everywhere page

### ISSUE THREAD

**Issue by katrinleinweber** [voc/streaming-website#104]
See [streaming.media.ccc.de](https://streaming.media.ccc.de/36c3/halla#chat) vs. [events.ccc.de/congress/2019/wiki/index.php/Congress_Everywhere](https://events.ccc.de/congress/2019/wiki/index.php/Congress_Everywhere#To_ask_a_question_in_a_talk) & [the blog](https://events.ccc.de/2019/12/26/36c3-asking-your-questions/) ("`#hallA`" vs. "`#Ada`").

Should/Can this be aligned by changing https://github.com/voc/streaming-website/blob/1493ed8cce3816411b16b8512144802cf12b6cfa/configs/conferences/36c3/config.php#L124-L137 to reduce confusion & workload for signal angels & Congress Everywhere participants?

**Comment by saerdnaer** [comment]
Hi @katrinleinweber,

can you provide a PR for the corresponding sections e.g. 

https://github.com/voc/streaming-website/blob/1493ed8cce3816411b16b8512144802cf12b6cfa/configs/conferences/36c3/config.php#L239-L246

Thanks in advance,
Andi

**Comment by katrinleinweber** [comment]
Thanks for the pointer :-)
