### ISSUE TITLE
404 on "camera icon link" until recordings are released

### ISSUE THREAD

**Issue by derpeter** [voc/streaming-website#19]
the link on top of the streaming website that points to media.ccc.de is a 404 until the first recordings are released. maybe it should point to relive or a page that offers relive and media links.

**Comment by saerdnaer** [comment]
We could also add and 'conference is still running' banner with a link to the streaming website

**Comment by derpeter** [comment]
which would make no sense as they are already on the streaming side so they knew it is still  running. But hey as long as you can replay to each and every report on github ....
