### ISSUE TITLE
Besseres Fehlverhalten bei Streamabbruch

### ISSUE THREAD

**Issue by MaZderMind** [voc/streaming-website#21]
Wenn ein Stream abbricht, soll die Webseite
 - 2x einen anderen Mirror probieren
 - nach 3 Fehlversuchen einen SD-Stream anbieten
 - einen Link zum Feedback-geben anbieten, welcher mit relevanten Infos angereichert ist (insb. Provider etc.)

**Comment by saerdnaer** [comment]
Sollte sich mit dem VOC-Player und DASH inzwischen erledigt haben
