### ISSUE TITLE
XSS Vulnerabilities from speaker provided Talk Titles

### ISSUE THREAD

**Issue by M4GNV5** [voc/streaming-website#231]
We found two XSS vulnerabilities related to talk title display in the fahrplan frontend:

The first one is caused by [this php code](https://github.com/voc/streaming-website/blob/8ef785d617f0d628ec88aef94cef3024edeb6671/template/assemblies/schedule.phtml#L50) which directly embeds Talk titles in php generated javascript.
Here is a screenshot from Firefox developer tools showing the generated code from todays talk `"Was sind eigentlich Audio Interventionen?" - Von Sound Grafitti und Protest-Jingles`

![image](https://github.com/voc/streaming-website/assets/5504713/093161b1-f380-4e1a-bf84-fbd7a9ebdea6)

The second one is caused by [this](https://github.com/voc/streaming-website/blob/8ef785d617f0d628ec88aef94cef3024edeb6671/assets/js/schedule.js#L77-L80) and [this javascript code](https://github.com/voc/streaming-website/blob/8ef785d617f0d628ec88aef94cef3024edeb6671/assets/js/schedule.js#L65) setting `.innerHTML` using unescpaed fahrplan data.

Using a malicious talk title a potential attacker could execute arbitrary javascript code in end-user browsers. Our attempts to verify this vulnerability were mitigated by speaker desks manual disapproval of changes to @k-gomez talk title.

**Comment by lukas2511** [comment]
I've added a small workaround for the first issue. We'll take a look at the other issues at a later time. Thanks for reporting.

**Comment by M4GNV5** [comment]
The string replacement does not seem to filter all cases. The HTML escape is handeled, but the JavaScript string can stil lbe escaped and used for XSS on mouse over. Example payload: `'}); alert(1); //` which will turn into:
`showEventDetails(event, {title:''}); alert(1); // ...`.

This also happens to break mouseover of todays talk `Back in the Driver's Seat: Recovering Critical Data from Tesla Autopilot Using Voltage Glitching`, because it includes a `'`

**Comment by lukas2511** [comment]
Single quotes are now also escaped. I'm mostly interested in keeping the site fully functional for now. The security issues will be fixed on a later date. They don't seem too criticial since for now a human remains in the loop.

The issue with existing escape functions is the nesting of json in an html argument, they behave differently and I'll need time and quiet to figure this out without introducing new issues.

**Comment by iSchluff** [comment]
fixed both the XSS in javascript and a further XSS in php via the talk title title attribute
