### ISSUE TITLE
Embed-Tab: Select-Box differiert von iframe-Code

### ISSUE THREAD

**Issue by Kunsi** [voc/streaming-website#29]
Beim Aufruf des Tabs ist im <select> 1920x1080 eingestellt, im <iframe> findet sich allerdings 1024x576. Der Standardwert des <iframe>s sollte ebenfalls 1920x1080 sein.

**Comment by MaZderMind** [comment]
Die wenigsten wollen tatsächlich einen 1920x1080 pixel großen iframe in ihren Blog einbinden sondern eine verkleinerte Ansicht. Klickt der Besucher jedoch auf den Fullscreen-Button, sieht er einen HD-Stream.

Daher sollte der Default immer 1024 sein und nie 1920.
