### ISSUE TITLE
Embed-Tab: Change to <object>

### ISSUE THREAD

**Issue by Kunsi** [voc/streaming-website#30]
Using a <object>-Tag should be more future-proof than using frames.

Old:
`<iframe src="https://streaming.media.ccc.de/33c3/embed/hall1/hd/native/" width="1024" height="576" frameborder="none" allowfullscreen="allowfullscreen" seamless="seamless" scrolling="no"></iframe>`

New:
`<object data="https://streaming.media.ccc.de/33c3/embed/hall1/hd/native/" type="text/html" width="1024" height="576" style="border: 0; overflow: hidden;"></object>`

**Comment by MaZderMind** [comment]
I don't see why a change to `<object>` would be beneficial.
`<iframe>` is valid according to the html5 spec:
https://www.w3.org/TR/html5/embedded-content-0.html#the-iframe-element
> The iframe element represents a nested browsing context.

Please provide reasoning and a browser compatibility indication on why we should switch to `<object>`
