### ISSUE TITLE
HTML5 player for ReLive

### ISSUE THREAD

**Issue by derrod** [voc/streaming-website#37]
Currently the ReLive site requires Flash. There are a few alternatives available now and it would be great to have a non-flash solution for the future.

For example MediaElement.js 3.x utilizes hls.js for HLS playback without flash in browsers that support MSE. A beta option akin to the DASH player option in live streams could work.

(If I'm at the wrong place here please let me know).

**Comment by florolf** [comment]
We're using an hls.js-based player now.
