### ISSUE TITLE
Try Clappr-Player for normal live streams

### ISSUE THREAD

**Issue by MaZderMind** [voc/streaming-website#39]
DASH and ReLive already use the new Clappr-Player. We should try to replace the MEJs-Player, too, to improve consistency.

**Comment by saerdnaer** [comment]
Potential blocker: Clappr currently has no support for subtitles: https://github.com/clappr/clappr/issues/1079

Ansonsten hört sich die Features/Plugins Liste am Ende von https://github.com/clappr/clappr und ein Blogeintrag zum Hintergrund http://blog.flavioribeiro.com/clappr-an-extensible-media-player-for-the-web/ ganz nett an...

**Comment by saerdnaer** [comment]
Ah sorry – hatte nicht gesehen das wir hier im streaming-website und nicht im voctoweb Repo sind.

**Comment by iSchluff** [comment]
mejs is mostly gone, just keeping it around atm for slides.
