### ISSUE TITLE
Feature request: Skip 10 seconds replay 10 seconds

### ISSUE THREAD

**Issue by PhilmacFLy** [voc/streaming-website#43]
Especially for long talks it would be nice to have a button to replay the last 10 seconds or skip 10 seconds.
I find my self often watching the videos on a second screen and doing something else on my main screen, if I miss a detail in a talk, I have to fiddle around with the progress bar to find the right position again.

**Comment by saerdnaer** [comment]
TODO: add following plugin https://github.com/johndyer/mediaelement-plugins/tree/master/src/skip-back

**Comment by PhilmacFLy** [comment]
Ah sorry, my bad. This should rather go to voctoweb then I guess

**Comment by saerdnaer** [comment]
'moved' to https://github.com/voc/voctoweb/issues/220
