### ISSUE TITLE
Streams-API v2

### ISSUE THREAD

**Issue by MaZderMind** [voc/streaming-website#6]
We should set up a v2 Streams-Api that incorporates the following changes:
- [x] Group by "conference" (because of new mandator-system)
- [ ] Rename "music" to "radio" (because there could also be audio-only streams with spoken content, see hack in 50c5c14865b7cbc9b9dc4bd5df01b4d71f77d5ae)
- [ ] tbc.

**Comment by johnjohndoe** [comment]
Feel free to test if [*Brockman*](https://github.com/johnjohndoe/Brockman) can still parse the API response. There also is the [*Brockman demo app* for Android](https://github.com/johnjohndoe/BrockmanDemo).

**Comment by MaZderMind** [comment]
@johnjohndoe I guess it won't, because "conference" will be a new hierarchy element necessary because we recently support having multiple conferences at the same point in time.

For this reason I'd add this as a new API named `/streams/v2.json`. This ticket is a collection of all changes that we might want to incorporate into this new api, giving consumers a place to learn early about them and also to add their own wishes.

**Comment by johnjohndoe** [comment]
Please note that you would have to [change the API path](https://github.com/johnjohndoe/BrockmanDemo/blob/master/app/build.gradle#L15) yourself to test the production endpoint.
