### ISSUE TITLE
Embed-URL auf Dash-Tab falsch

### ISSUE THREAD

**Issue by MaZderMind** [voc/streaming-website#63]
Die Embed-URL lautet dort z.B. https://streaming.media.ccc.de/ke1/embed/blackbox/dash/native – das /native hinten ist zu viel.

**Comment by MaZderMind** [comment]
Zur klärung: Das Embedding funktioniert, der Link ist nur unnötig lang

**Comment by iSchluff** [comment]
Die lange Embed-Url hat jetzt nachträglich einen Sinn erhalten: Man kann damit die präferierte Sprache des Dash-Embeds festlegen. D.h. mit /translated startet der Player auf der Translated-Spur falls diese existiert.
