### ISSUE TITLE
render streaming/recording optout flag in schedule

### ISSUE THREAD

**Issue by saerdnaer** [voc/streaming-website#88]
Offenbar zeigen wir im Schedule Renderer auf der streaming Website das Optout-Flag aktuell nicht mit an 
![image](https://user-images.githubusercontent.com/40266/50513080-d0bd9100-0a95-11e9-8672-c38cdbc8e04d.png)

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/40266/50513058-b1266880-0a95-11e9-8f0e-4fca520f71cc.png">

**Comment by dedeibel** [comment]
I am on it, talk to me if you are too

**Comment by dedeibel** [comment]
fixed in 811b6f7d444651aa6b92325a0cafda4d6cf0a22f
